#
# Makefile for Chapter 01
#
# Type  make    to compile all the programs
# in the chapter 
#
all: getint multiarray month_name echo1 echo2

clean:
	rm -f getint multiarray month_name echo1 echo2

getint:
	cc -o getint getint.c getch.c

multiarray: multiarray.c 
	cc -o multiarray multiarray.c 

month_name: month_name.c 
	cc -o month_name month_name.c 

echo1: echo1.c 
	cc -o echo1 echo1.c 

echo2: echo2.c 
	cc -o echo2 echo2.c 
